# Generated by Django 3.1.1 on 2021-03-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=60)),
                ('image', models.ImageField(null=True, upload_to='books')),
            ],
        ),
    ]
